"""Rebuild local evidence and browser export from frozen catalog and synthetic inputs."""
import argparse
from collections import Counter
from dataclasses import asdict
import hashlib
from importlib.metadata import version
import json
from pathlib import Path
import platform
import sqlite3
import pandas as pd
from src.demo import synthetic_case, selection_experiment, SEED
from src.events import ROOT, StudyConfig, load_catalog, study, LIMITATIONS
from src.store import connect, save_run, query_events, reconcile


def export(out, db_path):
    out,db_path=Path(out),Path(db_path)
    out.mkdir(parents=True,exist_ok=True); db_path.parent.mkdir(parents=True,exist_ok=True)
    schedule,returns,synthetic=synthetic_case()
    historical=load_catalog()
    # No provider prices are bundled. Preserve the historical catalog without inventing returns.
    empty=pd.DataFrame(index=schedule.index)
    rows=study(historical,empty,schedule)+study(synthetic,returns,schedule)
    inputs={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted((ROOT/'fixtures').glob('*')) if p.is_file()}
    inputs['synthetic_returns']=hashlib.sha256(returns.to_csv(float_format='%.17g').encode()).hexdigest()
    code={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
          for p in sorted((ROOT/'src').glob('*.py'))}
    manifest={'command':'python -m src.export', 'seed':SEED,'config':asdict(StudyConfig()),
              'versions':{p:version(p) for p in ['numpy','pandas','scipy','exchange-calendars']},
              'python':platform.python_version(),'sqlite':sqlite3.sqlite_version,
              'inputs_sha256':inputs,'code_sha256':code,
              'return_unit':'log return; CAR is an arithmetic sum, not a tradable P&L',
              'calendar':'XNYS regular sessions 2022-01-03 through 2025-12-31',
              'sample_dates':[str(schedule.index[0].date()),str(schedule.index[-1].date())]}
    db=connect(db_path)
    try:
        run_id=save_run(db,historical+synthetic,rows,manifest)
        reconcile(db,run_id,rows)
        saved=query_events(db,run_id)
    finally:
        db.close()
    counts={kind:{'catalog':sum(r['input_kind']==kind for r in saved),
                  'included':sum(r['input_kind']==kind and r['status']=='included' for r in saved),
                  'excluded_reasons':dict(Counter(r['reason'] for r in saved if r['input_kind']==kind and r['reason']))}
            for kind in ['historical','synthetic']}
    payload={'schema_version':1,'run_id':run_id,'manifest':manifest,'counts':counts,
             'limitations':LIMITATIONS,'selection_bias':selection_experiment(),'events':saved}
    (out/'results.json').write_text(json.dumps(payload,indent=2,allow_nan=False)+'\n')
    pd.DataFrame([{k:r.get(k) for k in ['id','symbol','input_kind','timestamp','aligned_session',
                  'status','reason','n_estimation','n_event','ar_day','car','car_se']} for r in saved]).to_csv(out/'results.csv',index=False,float_format='%.12g')
    included=[r for r in saved if r['status']=='included']
    table='| Input | Session | Estimation n | Event n | Day 0 AR | CAR [-2,+5] |\n|---|---|---:|---:|---:|---:|\n'
    for r in included:
        table+=f"| {r['symbol']} (synthetic) | {r['aligned_session']} | {r['n_estimation']} | {r['n_event']} | {r['ar_day']:.6%} | {r['car']:.6%} |\n"
    bias=payload['selection_bias']
    report=f'''# Recorded offline validation

Generated by `python -m src.export` with seed {SEED}. Run `{run_id}`.
Machine-readable inputs, SHA-256 hashes, configuration and versions: [results.json](results.json).
Full outcomes, including exclusions: [results.csv](results.csv).

{table}
The exact linear synthetic model has alpha 0.0002 and beta 1.3. Its residual
variance is zero up to rounding; near-zero interval widths validate arithmetic,
not real-market certainty. The no-shock control provides no trading-edge evidence.

Historical catalog: {counts['historical']['catalog']} records, {counts['historical']['included']} eligible CARs.
Seventeen records lack verified source/time. LUNR's documented after-hours landing
aligns from 2024-02-22 18:23 EST to 2024-02-23; historical prices are not bundled,
so its CAR remains excluded. Its occurrence time is not a first-publication time.

Selection-bias demonstration: {bias['candidate_count']} independent zero-mean normal draws,
sigma 1%, seed {SEED}. Mean of all draws: {bias['all_dates_mean']:.6%}; ten dates chosen
in advance: {bias['precommitted_mean']:.6%}; ten largest returns selected after seeing
prices: {bias['hindsight_top10_mean']:.6%}. This is an explicit hindsight-selection
experiment, not a list of catalyst events or a trading backtest.

{LIMITATIONS}
'''
    (out/'RESULTS.md').write_text(report)
    return payload


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,default=ROOT/'evidence')
    parser.add_argument('--db',type=Path,default=ROOT/'data/evidence.sqlite')
    args=parser.parse_args()
    result=export(args.out,args.db)
    print(json.dumps({'run_id':result['run_id'],'counts':result['counts'],'output':str(args.out)},indent=2))

if __name__=='__main__': main()
